### ISSUE TITLE
[ISSUE] Shell Crashes & Control Ribbon Issues

### ISSUE THREAD

**Issue by ytcalifax** [moudey/Shell#95]
## **Describe the bug**

* The beta release does indeed fix the CPU usage issue, however the missing buttons for closing/minimising/maximising is still an issue (if they do appear, it takes time); Moreover, when the app is injected into Windows I seem to hear my OS playing error/crash sounds in the background, which I can confirm to be an issue caused by the Shell, since explorer.exe crashing makes this sound.

---

### **To Reproduce**

1. Install "Shell"
2. Hook "Shell" into explorer.exe 
3. Use the "Shell" app
4. Wait a bit - you'll eventually hear an error sound and in Event Viewer you'll have this:
![image](https://user-images.githubusercontent.com/15365857/209973698-d23bf2e6-8b0c-4d3d-ae38-e0571be4143d.png)

---

### **Expected behaviour**

* The app should work properly without crashing the shell and causing the buttons for closing/minimising/maximising to be broken.

---

### **Your environment**

* OS: Windows 11 (22H2/22621.963) 
* CPU: Ryzen 5 5600X

---

**Comment by ytcalifax** [comment]
Another thing I notice is the fact that when I open a new File Explorer while the CPU usage is high the buttons for closing/minimising/maximising the window are completely gone.

**Comment by moudey** [comment]
This issue was fixed in the beta version. Please refer to this topic #37

**Comment by ytcalifax** [comment]
I am using the beta version (I replaced the old files with the new ones) and I still have the same issue

**Comment by moudey** [comment]
Please try this [build](https://github.com/moudey/Shell/files/10231493/shell-test.zip)

**Comment by ytcalifax** [comment]
I tried it but it seems to use a .nss (and not a .shl file), which leads to me losing all default stuff that I customised. The shell has not crashed yet, but I'll wait a little bit more before reporting back to you.

**Comment by ytcalifax** [comment]
Alright, the shell seems to no longer crash, however I don't have anything custom other than 1 single thing: 
![image](https://user-images.githubusercontent.com/15365857/209982312-0c507a7f-c47f-41d6-8942-c30ddc095e5f.png)
 
Is there at least a default config that matches the default one that the 1.7/1.8 beta use?

**Comment by moudey** [comment]
Please refer to this topic #66
